<?php
namespace Tests\Unit\Models\Factory;
use App\Models\Comic;
use App\Models\Factory\ComicFactory;
use Illuminate\Foundation\Testing\TestCase;

class ComicFactoryTest extends TestCase
{
    private $comicFactory;
    protected function setUp(): void
    {
        $this->comicFactory = new ComicFactory();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testCreate()
    {
        $fields = [
            'name' => 'Valerie',
            'description' => 'Some description',
            'adult' => false,
            'author' => 'Cat',
        ];
        $comic = $this->comicFactory->create($fields);
        $this->assertInstanceOf(Comic::class, $comic);
        $this->assertEquals($fields['name'], $comic->name);
        $this->assertEquals($fields['description'], $comic->description);
        $this->assertEquals($fields['author'], $comic->author);
        $this->assertEquals($fields['adult'], $comic->adult);

        $this->assertFalse((bool) $comic->hidden);
        $this->assertNotEmpty($comic->salt);
        $this->assertNotEmpty($comic->slug);
    }
}
