<?php

namespace Tests\Unit\Console\Commands;

use PHPUnit\Framework\TestCase;
use Prophecy\PhpUnit\ProphecyTrait;
use Prophecy\Prophet;

class SyncWithMangadexTest extends TestCase
{
    use ProphecyTrait;
    protected function setUp(): void
    {
        $this->prophet = new Prophet();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * A basic unit test example.
     */
    public function test_example(): void
    {

        $this->assertTrue(true);

    }
}
