version: '3.4'

services:
    cron:
        depends_on:
            - "db"
        build:
            context: ./..
            dockerfile: dev/cron.dockerfile
        restart: unless-stopped
        volumes:
            - ./..:/var/www/html
            - ./data/storage:/var/www/html/storage
            - ./data/composer:/root/.composer
    btd:
        image: schickling/beanstalkd
        ports:
            - "11300:1130"
    worker:
        depends_on:
            - "db"
            - "btd"
        restart: unless-stopped
        build:
            context: ./..
            dockerfile: dev/worker.dockerfile
        volumes:
            - ./..:/var/www/html
            - ./data/storage:/var/www/html/storage
            - ./data/composer:/root/.composer

    backend:
        depends_on:
            - "db"
        build:
            context: ./..
            dockerfile: dev/Dockerfile
        restart: unless-stopped
        ports:
            - "8880:80"
        volumes:
            - ./..:/var/www/html
            - ./data/storage:/var/www/html/storage
            - ./data/composer:/root/.composer

    db:
        image: mysql:8.0.40-debian
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/mysql:/home/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=pizza
            - MYSQL_USER=pizza
            - MYSQL_PASSWORD=password
        ports:
            -   "8806:3306"
