version: '3.4'

services:
    cron:
        build:
            context: ./..
            dockerfile: prod/cron.dockerfile
        restart: unless-stopped
        volumes:
            - ./..:/var/www/html
            - /mnt/manga:/var/www/html/storage/app/public/comics
            - /home/logs:/var/www/html/storage/logs
            - ./data/composer:/root/.composer
    btd:
        image: schickling/beanstalkd
        ports:
            - "11300:1130"
    worker:
        depends_on:
            - "btd"
        restart: unless-stopped
        build:
            args:
                user: "www-data"
                uid: 33
            context: ./..
            dockerfile: prod/worker.dockerfile
        volumes:
            - ./..:/var/www/html
            - /mnt/manga:/var/www/html/storage/app/public/comics
            - /home/logs:/var/www/html/storage/logs
            - ./data/composer:/root/.composer
    backend:
        build:
            context: ./..
            dockerfile: prod/Dockerfile
        restart: unless-stopped
        ports:
            - "8880:80"
        volumes:
            - ./..:/var/www/html
            - /mnt/manga:/var/www/html/storage/app/public/comics
            - /home/logs:/var/www/html/storage/logs
            - ./data/composer:/root/.composer
