version: '3.4'

services:
    backend:
        build:
            context: ./..
            dockerfile: prod/Dockerfile
        restart: unless-stopped
        ports:
            - "8880:80"
        volumes:
            - ./..:/var/www/html
            - /mnt/manga:/var/www/html/storage/app/public/comics
